In [1]:
import numpy as np

In [5]:
# 1) For a given numpy array, how will you change the dimensions to 5 using the existing parameters in the numpy array. 
my_array = np.array([[[[1,3,4]]]])

# numpy.array(my_array, ndmin=5)
# numpy.array(my_array, ndim=5)
# numpy.array(my_array, ndim=1)
# numpy.array(my_array, ndim= my_array.ndmin + 1)




In [6]:
np.array(my_array, ndmin=5)

array([[[[[1, 3, 4]]]]])

In [7]:
my_array.ndim

4

In [ ]:
# 2) For the given numpy arrays, Array1 and Array2, what will be the dot product for the same.
# Array1 = array([[1, 2, 3], [4, 5, 6]]) Array2 = array([[2, 3],[3, 2]])

# Keyerror
# Valueerror
# array([[ -9, 6, -1],[-12, 18, -7]])
# None of the Above

In [9]:
Array1 = np.array([[1, 2, 3], [4, 5, 6]])
Array2 = np.array([[2, 3],[3, 2]])


In [11]:
# np.dot(Array1, Array2)

# ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [13]:
# 3) In a given numpy array, using the slicing operations print the reverse of the array. 
array = np.array([10,3,1,203,404,204,20,302,30,402,192])

# array1[len(array1):0]
# array1[-1:-len(array1)]
# array[-1:0]
# array[::-1]


In [14]:
array[::-1]

array([192, 402,  30, 302,  20, 204, 404, 203,   1,   3,  10])

In [ ]:
# 4) What is the output of the below code:  a = [[1, 0], [0, 1]]  b = [[4, 1], [2, 2]]  np.dot(a, b)

# None of the above
# array([[4, 1],[2, 2]])
# array([[1, 1], [2, 2]])
# array([[4, 4],[2, 4]])


In [15]:
a = [[1,0],[0,1]]
b = [[4,1],[2,2]]

In [16]:
np.dot(a,b)

array([[4, 1],
       [2, 2]])

In [2]:
# 5) What is the output of the following code:         #######################################3*4*5*6#######################
# a = np.arange(3*4*5*6).reshape((3,4,5,6)) 
# b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3)) 
# np.dot(a, b)[2,3,2,1,2,2]

# 499128
# Value Error
# 909128
# 399118

In [3]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))

In [5]:
print(a)

[[[[  0   1   2   3   4   5]
   [  6   7   8   9  10  11]
   [ 12  13  14  15  16  17]
   [ 18  19  20  21  22  23]
   [ 24  25  26  27  28  29]]

  [[ 30  31  32  33  34  35]
   [ 36  37  38  39  40  41]
   [ 42  43  44  45  46  47]
   [ 48  49  50  51  52  53]
   [ 54  55  56  57  58  59]]

  [[ 60  61  62  63  64  65]
   [ 66  67  68  69  70  71]
   [ 72  73  74  75  76  77]
   [ 78  79  80  81  82  83]
   [ 84  85  86  87  88  89]]

  [[ 90  91  92  93  94  95]
   [ 96  97  98  99 100 101]
   [102 103 104 105 106 107]
   [108 109 110 111 112 113]
   [114 115 116 117 118 119]]]


 [[[120 121 122 123 124 125]
   [126 127 128 129 130 131]
   [132 133 134 135 136 137]
   [138 139 140 141 142 143]
   [144 145 146 147 148 149]]

  [[150 151 152 153 154 155]
   [156 157 158 159 160 161]
   [162 163 164 165 166 167]
   [168 169 170 171 172 173]
   [174 175 176 177 178 179]]

  [[180 181 182 183 184 185]
   [186 187 188 189 190 191]
   [192 193 194 195 196 197]
   [198 199 200 201 202 203]


In [4]:
np.dot(a, b)[2,3,2,1,2,2]

499128

In [ ]:
# 6) What will be output for the following code? import numpy as np a = np.array([3, 7, 32], dtype = complex) print(a)

# [ 3.0+0.j 7.0+0.j 32.0+0.j]
# [ 3.+0.j 7.+0.j 32.+0.j]
# Error
# [ 3.+0.k 7.+0.j 32.+0.l]


In [19]:
a = np.array([3, 7, 32], dtype=complex)
print(a)


[ 3.+0.j  7.+0.j 32.+0.j]


In [ ]:
# 7) How to replace all values greater than a given value with a given cutoff? 
# For example: In array ‘ar1’, replace all values greater than 30 to 30 and less than 10 to 10.
# Input: np.random.seed(100) ar1 = np.random.uniform(1,50, 20)

# None of the above              ##############################################clip-################
# np.clip(a, a_min=10, a_max=30)
# np.where(a < 10, 10, np.where(a > 30, 30, a))
# Both of the above

In [20]:
np.random.seed(100) 
a = np.random.uniform(1,50, 20)

In [21]:
np.clip(a, a_min=10, a_max=30)


array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

In [7]:
a = np.array([1,2,3,4,5])
np.clip(a,2,4)

array([2, 2, 3, 4, 4])

In [ ]:
# 8) For the given arrays, array1 and array2, if we stack the two arrays row wise, what will be the output? 
# array1 = np.array([[1,2],[3,4]]) array2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])

# None of the above
# array([[ 1, 2],[ 3, 4],[ 1, 2],[ 3, 4],[ 5, 6],[ 7, 8],[ 9, 10]]) 
# array([[ 1, 2, 3, 4],[ 1, 2, 3, 4],[ 5, 6, 7, 8],[ 9, 10]])
# array([[ 1, 2, 3, 4, 1], [2, 3, 4, 5, 6],[ 7, 8, 9, 10]])

In [22]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])

In [23]:
np.vstack((array1, array2))

array([[ 1,  2],
       [ 3,  4],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
# 9) For a given numpy array, how are you going to insert a new value at the specified position? 
# array = np.array([10,3,1,203,404,204,20,302,30,402,192])  
# Elem_to_be_inserted = [1,2,3,4]  The position to be inserted at = before 404 

# numpy.insert(array1, np.where(404), array2)
# numpy.insert(array2, np.index(404), array2)
# numpy.insert(array2, 404, array2)
# numpy.insert(array1, 4, array2)

In [26]:
array = np.array([10,3,1,203,404,204,20,302,30,402,192])
Elem_to_be_inserted = [1,2,3,4]


In [27]:
np.insert(array, 4, Elem_to_be_inserted)


array([ 10,   3,   1, 203,   1,   2,   3,   4, 404, 204,  20, 302,  30,
       402, 192])

In [ ]:
# 10) Create a 3x3 matrix using numpy, and all the values of the matrix must be a constant k.

# numpy.ones(3,3)
# numpy.random.random((3,3), ‘k’)
# numpy.eye(‘k’)
# numpy.full((3,3), ‘k’)


In [31]:
np.full((3,3),'k')


array([['k', 'k', 'k'],
       ['k', 'k', 'k'],
       ['k', 'k', 'k']], dtype='<U1')

In [ ]:
# 11) For the given python code that implements bubble sort, what will be the output for the given numpy array. 
# def bub_sort(array): for i in range(0, len(array)): for j in range(0, len(array) - i - 1): if array[j] < array[j + 1]: 
# temp = array[j] array[j] = array[j + 1] array[j+1] = temp return array my_array = numpy.array([20,14,25,16,45,60,12,9])

# array([ 9, 12, 14, 16, 20, 25, 45, 60])
# array([60, 45, 25, 20, 16, 14, 12, 9])
# array([60, 45, 20, 25, 16, 14, 12, 9])
# array([ 9, 12, 16, 14, 20, 25, 45, 60])
                                                   #####################bubble sort#######################

In [32]:
def bub_sort(array):
    for i in range(0, len(array)): # range bcm 0 to 8
        for j in range(0, len(array) - i - 1):
            if array[j] < array[j + 1]:
                temp = array[j]
                array[j] = array[j + 1]
                array[j + 1] = temp
    return array

my_array = np.array([20,14,25,16,45,60,12,9])
bub_sort(my_array)


array([60, 45, 25, 20, 16, 14, 12,  9])

In [ ]:
# 12) For a given numpy array of the shape (2,5) ,How will you reshape the array in the shape (5,2).

# numpy.reshape(5,2)
# numpy.reshape((2,5) == (5,2))
# numpy.shape(5,2)
# numpy.arange(5,2)

In [37]:
my_array = np.array([[20,14,25,16,45],[56,60,12,9,7]])

In [38]:
my_array.shape

(2, 5)

In [39]:
my_array.reshape(5,2)

array([[20, 14],
       [25, 16],
       [45, 56],
       [60, 12],
       [ 9,  7]])

In [ ]:
# 13) What will be the shape of the sample numpy array after flattening it? Sample = numpy.array([[1,2],[3,4],[5,6],[7,8]])

# array([1, 2, 3, 4, 5, 6, 7, 8])
# None of the above               #############################flattening###############################
# array([1, 2], [3, 4], [5, 6], [7, 8])
# array([1], [2], [3], [4], [5], [6], [7], [8])


In [41]:
Sample = np.array([[1,2],[3,4],[5,6],[7,8]])
Sample.flatten()
# it will become 1 dimension arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# 14) In the given array, how can we get the following output - array([2, 5, 8]). 
# Sample = numpy.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])

# array[0:3][1]
# None of the above
# array[[0:3], [1]]
# array[0:3, 1]

In [42]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])


arr[0:3, 1]


array([2, 5, 8])

In [ ]:
# 15) Given two numpy arrays, we will perform Horizontally stack the given arrays array1 and array2. 
# What will be the output of the above operation? The sample arrays are as follows. 
# Array1 = numpy.arange(20,2) Array2 = numpy.array([1,2,3,4,5,6,7,8,9,10])

# array([ 1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# array([[ 1, 3, 5, 7, 9, 11, 13, 15, 17, 19], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
# array([[ 1, 3, 5, 7, 9, 11, 13, 15, 17, 19], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
# None of the above

In [11]:
Arr1 = np.arange(1,20,2)       #############################(arange(20,2))##################
Arr2 = np.array([1,2,3,4,5,6,7,8,9,10])


In [12]:
print(Arr1)

[ 1  3  5  7  9 11 13 15 17 19]


In [47]:
np.hstack((Arr1, Arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# 16) For the given arrays, array1 and array2, if we stack the two arrays column wise, what will be the output? 
# array1 = np.array([[1,2],[3,4]]) array2 = np.array([[5,6],[7,8]])

# array([[1, 2, 5, 6 ,3, 4, 7, 8]])
# array([[1, 2, 5, 6],[3, 4, 7, 8]])
# array([[1, 2], [5, 6],[3, 4], [7, 8]])
# None of the above

In [49]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])


In [50]:
np.column_stack((array1, array2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
# 17) Given two vectors A and B, find the cross product between the two vectors. 
# A = numpy.array([[4],[12],[29]]) B = numpy.array([[13],[21],[4]])
                                  ############# Cross vector ##########
# array([[-561 360 -72]])
# array([[-560 360 -71]])
# array([[-561 361 -72]])
# array([[-555 361 -72]])

In [51]:
A = np.array([[4],[12],[29]])
B = np.array([[13],[21],[4]])


In [52]:
np.cross(A.flatten(), B.flatten())

array([-561,  361,  -72])

In [ ]:
# 18) Given two vectors A and B, find the correlation coefficient of the following vectors.
# A = numpy.array([1,3,5,7,9,11,13,15,17,19,21,23,25]) B = numpy.array([0,2,4,6,8,10,12,14,16,18,20, 22, 24])
                              ################## corr coeff vector ################
# array([[1., 1.],[0., 1.]])
# array([[0., 1.],[1., 1.]])
# array([[1., 0.],[1., 1.]])
# array([[1., 1.],[1., 1.]])

In [53]:
A = np.array([1,3,5,7,9,11,13,15,17,19,21,23,25])
B = np.array([0,2,4,6,8,10,12,14,16,18,20, 22, 24])


In [54]:
np.corrcoef(A, B)

array([[1., 1.],
       [1., 1.]])

In [ ]:
# 19) Create a nested numpy array from a given dictionary data. 
# sample = {1: [1,2], 2: [[1],[2]], 3: [[1,2], [3,4], [4,5]], 4: [1], 5: [1,2,3,4,5]}
                                                            ####### comp ###############
# array([[1, list([1, 2])], [2, list([[1], [2]])], [3, list([[1, 2], [3, 4], [4, 5]])], [4, list([1])], [5, list([1, 2, 3, 4, 5])]], dtype=object)
# array([[1, list([1, 2])], [2, list([[1], [2]])], [3, list([[1, 2], [1, 4], [4, 5]])], [4, list([1])], [5, list([1, 2, 3, 4, 5])]], dtype=object)
# array([[1, list([1, 1])], [2, list([[1], [2]])], [3, list([[1, 2], [3, 4], [4, 5]])], [4, list([1])], [5, list([1, 2, 3, 4, 5])]], dtype=object)
# array([[1, list([1, 2])], [2, list([[1], [2]])], [3, list([[1, 2], [3, 4], [4, 5]])], [4, list([1])], [5, list([1, 2, 3, 10, 5])]], dtype=object)

In [14]:
sample = {1: [1,2], 2: [[1],[2]], 3: [[1,2], [3,4], [4,5]], 4: [1], 5: [1,2,3,4,5]}
np.array(list(sample.items()), dtype=object)
#np.array(list(sample), dtype=object)

array([[1, list([1, 2])],
       [2, list([[1], [2]])],
       [3, list([[1, 2], [3, 4], [4, 5]])],
       [4, list([1])],
       [5, list([1, 2, 3, 4, 5])]], dtype=object)

In [58]:
# 20) A 2-dimensional array with 3 rows and 3 columns containing random numbers from 1 to 9 is given as
# arr1= np.array([[3,2,1],[6,4,5],[8,7,9]])
# Find the difference between the maximum element across the columns and the minimum element across the rows.
                              
# [8 3 2]
# [7 3 1]
# [7 3 2]
# [7 1 2]

In [63]:
arr1 = np.array([[3,2,1],[6,4,5],[8,7,9]])
np.max(arr1, axis=0) - np.min(arr1, axis=1)


array([7, 3, 2])

In [64]:
# axis = 0 indicates across columns
# axis = 1 indicates across rows