# Load in Numpy 

In [1]:
import numpy as np

Why is numpy faster then list?



*Faster to read less bytes of memory,  
  *No type checking when iterating through objects,  
*numpy really on contiguous- memory--lists really on scartted memory, 
  *SIMD vector processing,
  *Effective Cache utilization

Applications of numpy?

1Mathematics (MATLAB Replacement)
  2Backend work
  3Store integers
  4Machine learning

# The Basics

In [8]:
a = np.array([1,2,3])
print(a)

# if we want decide data type
# a = np.array([1,2,3],  dtype='int16')
# print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# get dimenstion
a.ndim

1

In [6]:
# get shape
b.shape

(2, 3)

In [7]:
# get type
a.dtype

dtype('int32')

In [9]:
# get size
a.itemsize

4

In [17]:
b.itemsize

8

In [16]:
#get total size
#a.size * a.itemsize (same func)
a.nbytes

12

# Accessing/Changing specific elements, rows, columns, etc


In [18]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [19]:
a.shape

(2, 7)

In [20]:
# get specific element [r,c]
a[1,5]

13

In [22]:
a[1,-2]

13

In [23]:
# get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
# get a specific column
a[:, 2]

array([ 3, 10])

In [27]:
# getting a little more fancy [startindex:endingindex:stepindex]
a[0,1:6:2]

array([2, 4, 6])

In [31]:
a[0,1:-1:2]    # getting by negatice

array([2, 4, 6])

In [32]:
a[1,5] = 20         # change 13 to 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [36]:
a[:,2] = 5  # change the complete row to 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


# 3D-example

In [37]:
b = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [38]:
# get specific element (work outside in)
b[0,1,1]

4

In [40]:
b[:,1,:]

array([[3, 4]])

In [45]:
# replace
b[:,1,:] = [[9,9]]

In [46]:
b

array([[[1, 2],
        [9, 9],
        [5, 6],
        [7, 8]]])

# Initialzation Different types of array

In [48]:
# All 0s matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [51]:
# All 1s matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [50]:
# All 1s matrix
np.ones((2,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]])

In [52]:
# any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [53]:
# any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [54]:
# any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [55]:
# random decimal number
np.random.random((4,2))

array([[0.54367936, 0.29995803],
       [0.29932886, 0.67415896],
       [0.66076894, 0.42868191],
       [0.40216841, 0.47317455]])

In [56]:
np.random.rand(4,2)          # dont know the diff

array([[0.65509584, 0.94072895],
       [0.11290301, 0.04337796],
       [0.27996756, 0.20078734],
       [0.73041069, 0.89902944]])

In [61]:
# random integer numbers
np.random.randint(7,size=(2,3))

array([[2, 1, 4],
       [4, 1, 4]])

In [62]:

np.random.randint(-3,8,size=(3,3))

array([[-1,  4,  4],
       [ 3, -3,  0],
       [-2, -3,  1]])

In [64]:
# the indentity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [69]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [72]:
# ques making an massive array

output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [75]:
output[1:4,1:4] = z     # as negative [1:4,1:-1] 
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#  Be carefull when copying array!!1

In [76]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [77]:
b[0] = 100   # with chamgimg b , a is also change value
print(a)

[100   2   3]


In [79]:
c= np.array([1,8,7])  # now value not changing
d = c.copy()
d

array([1, 8, 7])

In [80]:
d[0]= 100
print(c)

[1 8 7]


#  Mathematics

In [82]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [83]:
a+2

array([3, 4, 5, 6])

In [84]:
a-2

array([-1,  0,  1,  2])

In [85]:
a*2

array([2, 4, 6, 8])

In [86]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [87]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [88]:
a ** 2

array([ 1,  4,  9, 16])

In [93]:
# take the sin
print("Cos(a) = :", np.cos(a))
print("Sin(a) = :", np.sin(a))
print("Tan(a) = :", np.tan(a))

Cos(a) = : [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
Sin(a) = : [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Tan(a) = : [ 1.55740772 -2.18503986 -0.14254654  1.15782128]


# Linear Algebra

In [94]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [96]:
# array multiply function
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [99]:
# Find the detterminant
c = np.identity(3)
print(c)

np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [100]:
## reference docs (http://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# determinant
# trace
# singular vector decompostiton
# eiggenvalues
# matrix norm
# inverse
# etc

# Statistics

In [101]:
stats = np.array([[1,2,3,4],[5,6,7,8]])
stats

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [102]:
np.min(stats)

1

In [105]:
np.min(stats, axis=1)

array([1, 5])

In [103]:
np.max(stats)

8

In [106]:
np.max(stats, axis = 0)

array([5, 6, 7, 8])

In [107]:
np.sum(stats, axis = 0)

array([ 6,  8, 10, 12])

In [108]:
np.sum(stats)

36

# Reorganizing Arrays

In [111]:
before = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(before)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [112]:
print(before.shape)

(2, 5)


In [114]:
after = before.reshape((5,2))
print(after)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [115]:
# vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [117]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

Load Data from file

np.genfromtxt('data.txt', delimiter=',')

# boolean masking and advanced indexing


In [118]:
# filedata > 50    (from text file ,loaded earlier)

In [119]:
# you can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

# Assignment 2 – NumPy

1. Create a 3x3 matrix array with values ranging from 2 to 10.

In [3]:
arr = np.arange(2, 11).reshape(3, 3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


2. Create a NumPy array having user input values and convert the integer
type to the float type of the elements of the array. For instance:

Original
array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]


In [4]:
x = np.array([1, 2, 3, 4])
arr = x.astype(np.float32)
print(arr)

[1. 2. 3. 4.]


3. Write a NumPy program to append values to the end of an array.

For
instance: Original array: [10, 20, 30] . After that, append values to the end
of the array: [10 20 30 40 50 60 70 80 90]


In [5]:
x = np.array([10, 20, 30])
y = np.append(x, [40, 50, 60, 70, 80, 90])
print(x)
print(y)

[10 20 30]
[10 20 30 40 50 60 70 80 90]


4. Create two NumPy arrays and add the elements of both the arrays and store the result in sumArray.


In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
sum_arr = arr1 + arr2

print(arr1)
print(arr2)
print(sum_arr)

[1 2 3]
[4 5 6]
[5 7 9]


5. Create a 3x3 array having values from 10-90 (interval of 10) and store that
in array1

Perform the following tasks:
    
a. Extract the 1st row from the array
b. Extract the last element from the array


In [10]:
arr1 = np.arange(10, 100, 10).reshape(3, 3)
print(arr1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [11]:
f_row = arr1[0, :]
f_row

array([10, 20, 30])

In [12]:
last_r = arr1[-1,-1]
last_r

90

# Case Study Problem 1

In [13]:
# 1. Create a function that takes dimensions as tuples e.g. (3, 3) and a numeric
# value and returns a NumPy array of the given dimension filled with the
# given value e.g.: solve((3, 3), 5) will return
# [
# [5, 5, 5],
# [5, 5, 5],
# [5, 5, 5]
# ]

In [17]:
def created_fill_arr(dimensions, value):
    return np.full(dimensions, value)

In [19]:
arr = created_fill_arr((3, 3),5)
arr

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
#2. Create a method that takes n NumPy arrays of the same dimensions,sums them and returns the answer.

In [20]:
def sum_arr(*arrays):
    if not all(arr.shape == arrays[0].shape for arr in arrays):
        raise ValueError("All arrays must have the same dimensions.")
    return np.sum(arrays, axis=0)

In [22]:
# sum of two arrays
xx = np.array([[1, 2], [3, 4]])
yy = np.array([[5, 6], [7, 8]])
sum_arrs = sum_arr(xx,yy)
print(sum_arrs)

[[ 6  8]
 [10 12]]


In [23]:
# 3. Given a 2 D Array of N X M Dimension, write a function that accepts this
# array as well as two numbers N and M. The method should return the
# top-left N X M sub matrix, e.g:
# [
# [1, 2, 3],
# [4, 5, 6],
# [7, 8, 9],
# ]
# top_left_sub_matrix (matrix, 2, 2) -> should return:
# [
# [1, 2]
# [4, 5]
# ]

In [24]:
def top_left_sub_matrix(matrix,n ,m):
    return matrix[:n, :m]

In [25]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
top_left = top_left_sub_matrix(matrix, 2, 2)
print(top_left)

[[1 2]
 [4 5]]


In [27]:
# 4. Given a 2 D Array of N X M Dimension, write a function that accepts this
# array as well as two numbers N and M. The method should return the
# bottom-right N X M sub matrix, e.g:
# [
# [1, 2, 3],
# [4, 5, 6],
# [7, 8, 9],
# ]
# sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are
# zero indexed)
# [
# [5, 6]
# [8, 9]
# ]

In [26]:
def bottom_right_sub_matrix(matrix, n, m):
    return matrix[-n:, -m:]

In [28]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
bottom_right = bottom_right_sub_matrix(matrix, 1, 1)
print(bottom_right)

[[9]]


In [29]:
# 5. Given a 1 D NumPy Array. Write a function that accepts this array as
# parameters. The method should return a dictionary with 'mean' and
# 'std_dev' as key and array's mean and array's standard deviation as
# values:
# [1, 1, 1]
# solution(arr) -> should return :
# {'mean': 1.0, 'std_dev': 0.0}

In [30]:
def get_mean_std_dev(array):
    mean = np.mean(array)
    std_dev = np.std(array)
    return {'mean': mean, 'std_dev': std_dev}

In [31]:
array = np.array([1, 1, 1])
stats = get_mean_std_dev(arr)
print(stats)

{'mean': 5.0, 'std_dev': 0.0}
